In [3]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from datetime import datetime
import datetime

import pandas as pd
from bs4 import BeautifulSoup

In [5]:
browser=webdriver.Chrome()

In [6]:
browser.get('https://www.tripadvisor.in/Hotels-g186338-London_England-Hotels.html')

In [7]:
accept = browser.find_element(By.ID, "onetrust-accept-btn-handler")
accept.click()

In [8]:
bsobj = BeautifulSoup(browser.page_source, 'lxml')

In [9]:
hotel = []
for name in bsobj.findAll('div',{'class':'listing_title'}):
  hotel.append(name.text.strip())

In [10]:
ratings = []
for rating in bsobj.findAll('a',{'class':'ui_bubble_rating'}):
  ratings.append(rating['alt'])

In [11]:
reviews = []
for review in bsobj.findAll('a',{'class':'review_count'}):
  reviews.append(review.text.strip())

In [12]:
price = []
for p in bsobj.findAll('div',{'class':'price-wrap'}):
  price.append(p.text.replace('₹','').strip()) 
price[:5]

['€112', '€208', '€144', '€185€142', '€295']

In [13]:
d1 = {'Hotel':hotel,'Ratings':ratings,'No_of_Reviews':reviews,'Price':price}
df = pd.DataFrame.from_dict(d1)

In [14]:
df

,Hotel,Ratings,No_of_Reviews,Price
0,Sponsored YOTEL London Shoreditch,4.5 of 5 bubbles,684 reviews,€112
1,1. The Montcalm Royal London House,5 of 5 bubbles,"3,351 reviews",€208
2,2. Park Grand London Hyde Park,4 of 5 bubbles,"3,362 reviews",€144
3,3. Park Grand Paddington Court,4.5 of 5 bubbles,"3,206 reviews",€185€142
4,4. The Resident Covent Garden,5 of 5 bubbles,"1,241 reviews",€295
5,5. Travelodge London City hotel,4.5 of 5 bubbles,"2,376 reviews",€59
6,"Sponsored The Biltmore Mayfair, LXR Hotel...",4 of 5 bubbles,173 reviews,€930
7,6. Canopy by Hilton London City,5 of 5 bubbles,420 reviews,€195
8,7. Hard Rock Hotel London,4.5 of 5 bubbles,"2,231 reviews",€388
9,8. The Montcalm London Marble Arch,5 of 5 bubbles,"3,810 reviews",€477
10,9. The Tower Hotel,4 of 5 bubbles,"12,227 reviews",€146
11,10. Travelodge London Docklands Central,4 of 5 bubbles,568 reviews,€78
12,"11. The Clermont, Charing Cross",5 of 5 bubbles,"6,711 reviews",€387
13,12. Leonardo Royal Hotel London St. Paul's,4 of 5 bubbles,"1,451 reviews",€225
14,13. Leonardo Royal London Tower Bridge,4 of 5 bubbles,"2,145 reviews",€169
15,14. Holiday Inn London - West,4.5 of 5 bubbles,"1,280 reviews",€99
16,15. Royal National Hotel,3 of 5 bubbles,"10,756 reviews",€218
17,16. The Montague on The Gardens,5 of 5 bubbles,"5,445 reviews",€336€314
18,17. Travelodge London Central City Road,4 of 5 bubbles,"2,198 reviews",€74
19,18. Park Plaza Westminster Bridge London,4.5 of 5 bubbles,"23,706 reviews",€302
20,19. Millennium Gloucester Hotel London Kensington,4 of 5 bubbles,"6,712 reviews",€154€144
21,"20. The Standard, London",4.5 of 5 bubbles,494 reviews,€261
22,Sponsored Mercure London Bridge,4.5 of 5 bubbles,438 reviews,€203
23,21. Travelodge London Manor House,4.5 of 5 bubbles,262 reviews,€94
24,22. The Bailey's Hotel London Kensington,4.5 of 5 bubbles,"1,923 reviews",€247
25,23. The Clarendon,4 of 5 bubbles,"2,943 reviews",€155
26,24. The President Hotel,3.5 of 5 bubbles,"4,702 reviews",€194
27,25. Grand Royale London Hyde Park,4 of 5 bubbles,"5,416 reviews",€149€131
28,26. Premier Inn London Hendon (The Hyde) hotel,4 of 5 bubbles,841 reviews,€75
29,27. Travelodge London Covent Garden,4 of 5 bubbles,"12,301 reviews",€90
30,28. St. Athans Hotel,4 of 5 bubbles,855 reviews,€117€109
31,29. Novotel London West,4 of 5 bubbles,"5,318 reviews",€186
32,30. easyHotel London City Shoreditch,4 of 5 bubbles,343 reviews,€99

In [15]:
df.to_csv("tripadvisor_london_list.csv")